### PR TITLE
Add missing stopwords to fix pod-spelling test

### PR DESCRIPTION
**Pull request by vanstyn**

### CODE REVIEW

**Comment by theory** [comment]
Thanks!

**Comment by vanstyn** [comment]
No problem... FYI, your module is now a Catalyst dep, so anyone who has Test::Spelling installed will get failures when installing/upgrading without this fix, so you might want to get this out to CPAN sooner than later... Also, you might want to think about skipping the test unless the env variable ```RELEASE_TESTING``` is set to prevent that type of problem in the future (I thought about doing that in the PR, but I didn't want to presume that style on your behalf)

@jjn1056  fyi

**Comment by theory** [comment]
Actually, the fact that the latest release included the spelling tests was an oversight. They will not be in the next release.

**Comment by jjn1056** [comment]
@theory, Catalyst current maintainer here, do you think you'll be doing an update sooner rather than later?  Right now Catalyst is broken for a percentage of people, install wise and I can't let that continue.  If you don't have time for this module, would you mind share co-maint with someone in the Catalyst cabal?  Otherwise I'll need to remove this dependency from Catalyst and localize it, which would be sad since it would mean CPAN has two versions of exactly the same thing :(

**Comment by theory** [comment]
Already gave co-maint to @ap, but will push out a release myself today.

**Comment by karenetheridge** [comment]
thumbs up to this whole thread. spelling tests should be in xt/ or guarded with a skip_all unless $ENV{AUTHOR_TESTING}.

**Comment by theory** [comment]
v0.13 is on its way to CPAN now.

**Pull request merged**
